---
- name: Get Hostname
  become: true
  hosts: rhel7_64Guest
  tasks :
    - name: Get Hostname via shell
      command: hostname
      register: result
    - name: write result
      debug:
        msg: "Complete for {{ result.stdout.split('\n') }} "
#        var: result
#        verbosity: 2